authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit, verify

app_name = 'authapp'

urlpatterns = [

    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from mainapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('admin/', include('adminapp.urls', namespace='admin')),

    path('', views.index, name='index'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),

    path('contact/', views.contact, name='contact'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import timedelta
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


def get_activation_key_expiration_date():
    return now() + timedelta(days=2)


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users', blank=True, verbose_name='Аватарка')
    age = models.PositiveSmallIntegerField(verbose_name='Возраст')

    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=get_activation_key_expiration_date)

    def is_activation_key_expired(self):
        if now() <= self.activation_key_expires:
            return False
        return True


class ShopUserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж'),
    )

    user = models.OneToOneField(ShopUser, unique=True, null=False, db_index=True, on_delete=models.CASCADE)

    tagline = models.CharField(verbose_name='тэги', max_length=128, blank=True)

    about_me = models.TextField(verbose_name='о себе', max_length=512, blank=True)

    gender = models.CharField(verbose_name='пол', max_length=1, choices=GENDER_CHOICES, blank=True)

    @receiver(post_save, sender=ShopUser)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            ShopUserProfile.objects.create(user=instance)

    @receiver(post_save, sender=ShopUser)
    def save_user_profile(sender, instance, **kwargs):
        instance.shopuserprofile.save()

authapp/forms.py
import hashlib
import random

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from django import forms
from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'age', 'avatar', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_age(self):
        current_age = self.cleaned_data['age']
        if current_age < 18:
            raise forms.ValidationError('Вы слишком молоды для этого')

        return current_age

    def save(self):
        user = super(ShopUserRegisterForm, self).save()
        user.is_active = False

        salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1(str(user.email + salt).encode('utf8')).hexdigest()
        user.save()

        return user


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        current_age = self.cleaned_data['age']
        if current_age < 18:
            raise forms.ValidationError('Вы слишком молоды для этого')

        return current_age

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth

from authapp.models import ShopUser
from authapp.utils import send_verify_mail
from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm


def login(request):
    login_form = ShopUserLoginForm(data=request.POST)

    next_url = request.GET.get('next', '')

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST.get('next'))
            return HttpResponseRedirect(reverse('index'))

    context = {
        'form': login_form,
        'title': 'Вход в систему',
        'next': next_url
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            user = register_form.save()
            if send_verify_mail(user):
                print("сообщение отправлено")
                return HttpResponseRedirect(reverse('auth:login'))
            else:
                print('ERROR: отправки почты')
                return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    context = {
        'form': register_form,
        'title': 'Регистрация',
    }

    return render(request, 'authapp/register.html', context)


def edit(request):
    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('authapp:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    context = {
        'form': edit_form,
        'title': 'Редактирование профиля'
    }

    return render(request, 'authapp/edit.html', context)


def verify(request, email, activation_key):
    try:
        user = ShopUser.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            user.is_active = True
            user.save()
            auth.login(request, user)
            return render(request, 'authapp/verification.html')
        else:
            print(f'error activation user: {user}')
            return render(request, 'authapp/verification.html')
    except Exception as err:
        print(f'error activation user: {err.args}')
        return HttpResponseRedirect(reverse('index'))

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="login">
        <div class="h2 text-center head">
            {{ title }}
        </div>
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}

{% block content %}
    <form class="form-horizontal col-10" method="post" action="{% url 'authapp:edit' %}"
          enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Сохранить</button>
    </form>
    <div class="user_avatar">
    <a class="btn btn-link" href="{% url 'index' %}" style="width: 100%">На главную</a>
    </div>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% block content %}
    <form class="form-horizontal col-10" method="post" action="{% url 'authapp:login' %}">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" value="{{ next }}" name="next">
        {% endif %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Войти</button>
    </form>

    <a class="btn btn-info" href="{% url 'authapp:register' %}" style="width: 100%">Зарегистрироваться</a>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}

{% block content %}
    <form class="form-horizontal col-10" method="post" action="{% url 'authapp:register' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Зарегистрироваться</button>
    </form>

    <a class="btn btn-info" href="{% url 'authapp:login' %}" style="width: 100%">Войти</a>
{% endblock %}

authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}

  {% if user %}
    <h3>Поздравляем!</h3>
    <br>
    <h4>Пользователь {{user.username}} подтвержден.</h4>
  {% else %}
    <h3>Верификация не пройдена.</h3>
  {% endif %}
  <br>
  <button class="btn btn-round form-control">
    <a href="{% url 'index' %}" class="">на главную</a>
  </button>

{% endblock %}