adminapp/urls.py
from django.urls import path
from adminapp import views as adminapp

# urlpatterns = [
#     path('users/create/', adminapp.user_create, name='user_create'),
#     path('users/read/', adminapp.user_read, name='user_read'),
#     path('users/update/<pk>', adminapp.user_update, name='user_update'),
#     path('users/delete/<pk>', adminapp.user_delete, name='user_delete'),
# ]


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.user_read, name='user_read'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
]

authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit, verify

app_name = 'authapp'

urlpatterns = [

    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from mainapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('admin/', include('adminapp.urls', namespace='admin')),

    path('', views.index, name='index'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),

    path('contact/', views.contact, name='contact'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/views.py
from django.shortcuts import render


def user_create(request):
    return None


def user_read(request):
    return None


def user_update(request, pk):
    return None


def user_delete(request, pk):
    return None

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
                {{ title|title }}
            {% endblock %}
        </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
    </head>
<body>
    <div class="admin_container">
        <div class="h2 text-center head">
            Админка
        </div>
        {% block menu %}
            <div class="admin_menu">
                {% include 'adminapp/includes/inc_menu.html' %}
            </div>
        {% endblock %}
        {% block content %}
        {% endblock %}
</div>
</body>
</html>

adminapp/templates/adminapp/user_list.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="users_list">
        <button class="new_user">
            <a href={% url 'adminapp:user_create' %}>
                новый пользователь
            </a>
        </button>
        {% for object in objects %}
            <div
                    class="user_record {% if not object.is_active %}not_active{% endif %}">
                <img
                        src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}"
                        alt="{{ object.username }}">
                <div class="user_role">
                    {% if object.is_superuser %}
                        администратор
                    {% else %}
                        пользователь
                    {% endif %}
                    <button>
                        <a href={% url 'adminapp:user_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href={% url 'adminapp:user_delete' object.pk %}>
                            удалить
                        </a>
                    </button>
                </div>
                <div class="user_name">
                    <p><strong>{{ object.username }}</strong></p>
                    <p>
                        {% if object.first_name %}
                            <b>{{ object.first_name|title }}</b>
                            {% if object.last_name %}
                                <p>{{ object.last_name|title }}</p>
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
                <div class="user_age">
                    age:<br>
                    {{ object.age }} лет
                </div>
                <div class="user_email">
                    email:<br>
                    {{ object.email }}
                </div>
                <div class="user_lastlogin">
                    logged:<br>
                    {{ object.last_login }}
                </div>
            </div>
        {% endfor%}
    </div>
{% endblock %}